---
- name: Deploy Caddy environment file
  ansible.builtin.template:
    src: caddy.env.j2
    dest: "{{ xcaddy_environment_file }}"
    owner: "{{ xcaddy_user }}"
    group: "{{ xcaddy_group }}"
    mode: "0640"
  become: true
  when:
    - xcaddy_environment_file | length > 0
    - xcaddy_environment | length > 0
  notify: Restart Caddy

- name: Deploy Caddy systemd service unit
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Reload systemd daemon
    - Restart Caddy

- name: Enable Caddy service
  ansible.builtin.systemd_service:
    name: caddy
    enabled: "{{ xcaddy_service_enabled }}"
  become: true

- name: Start Caddy service
  ansible.builtin.systemd_service:
    name: caddy
    state: started
  become: true
  when: xcaddy_service_started
