---
- name: Verify xcaddy role installation
  hosts: all
  become: true
  vars:
    expected_caddy_version: 'v2.10.2'
    expected_module: 'github.com/caddy-dns/cloudflare'
  tasks:
    # Verify Caddy binary
    - name: Check Caddy binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/caddy
      register: caddy_binary

    - name: Assert Caddy binary exists
      ansible.builtin.assert:
        that:
          - caddy_binary.stat.exists
          - caddy_binary.stat.executable
        fail_msg: 'Caddy binary not found or not executable at /usr/local/bin/caddy'
        success_msg: 'Caddy binary exists and is executable'

    # Verify Caddy version
    - name: Get Caddy version
      ansible.builtin.command:
        cmd: /usr/local/bin/caddy version
      register: caddy_version_output
      changed_when: false

    - name: Assert Caddy version is correct
      ansible.builtin.assert:
        that:
          - expected_caddy_version in caddy_version_output.stdout
        fail_msg: 'Expected Caddy version {{ expected_caddy_version }}, got: {{ caddy_version_output.stdout }}'
        success_msg: 'Caddy version is correct: {{ caddy_version_output.stdout }}'

    # Verify Caddy modules
    - name: Get Caddy modules
      ansible.builtin.command:
        cmd: /usr/local/bin/caddy list-modules --packages --skip-standard
      register: caddy_modules_output
      changed_when: false

    - name: Assert expected module is installed
      ansible.builtin.assert:
        that:
          - expected_module in caddy_modules_output.stdout
        fail_msg: 'Expected module {{ expected_module }} not found in: {{ caddy_modules_output.stdout }}'
        success_msg: 'Expected module {{ expected_module }} is installed'

    # Verify config directory and Caddyfile
    - name: Check config directory exists
      ansible.builtin.stat:
        path: /etc/caddy
      register: config_dir

    - name: Assert config directory exists
      ansible.builtin.assert:
        that:
          - config_dir.stat.exists
          - config_dir.stat.isdir
        fail_msg: 'Config directory /etc/caddy does not exist'
        success_msg: 'Config directory /etc/caddy exists'

    - name: Check Caddyfile exists
      ansible.builtin.stat:
        path: /etc/caddy/Caddyfile
      register: caddyfile

    - name: Assert Caddyfile exists
      ansible.builtin.assert:
        that:
          - caddyfile.stat.exists
        fail_msg: 'Caddyfile not found at /etc/caddy/Caddyfile'
        success_msg: 'Caddyfile exists at /etc/caddy/Caddyfile'

    # Verify Caddy config is valid
    - name: Validate Caddy config
      ansible.builtin.command:
        cmd: /usr/local/bin/caddy validate --config /etc/caddy/Caddyfile
      register: caddy_validate
      changed_when: false

    - name: Assert Caddy config is valid
      ansible.builtin.assert:
        that:
          - caddy_validate.rc == 0
        fail_msg: 'Caddy config validation failed: {{ caddy_validate.stderr }}'
        success_msg: 'Caddy config is valid'

    # Verify service file exists
    - name: Check service file exists
      ansible.builtin.stat:
        path: /etc/systemd/system/caddy.service
      register: service_file

    - name: Assert service file exists
      ansible.builtin.assert:
        that:
          - service_file.stat.exists
        fail_msg: 'Service file not found at /etc/systemd/system/caddy.service'
        success_msg: 'Service file exists at /etc/systemd/system/caddy.service'

    # Verify caddy user and group
    - name: Check caddy user exists
      ansible.builtin.getent:
        database: passwd
        key: caddy
      register: caddy_user

    - name: Assert caddy user exists
      ansible.builtin.assert:
        that:
          - caddy_user is not failed
        fail_msg: 'Caddy user does not exist'
        success_msg: 'Caddy user exists'

    - name: Check caddy group exists
      ansible.builtin.getent:
        database: group
        key: caddy
      register: caddy_group

    - name: Assert caddy group exists
      ansible.builtin.assert:
        that:
          - caddy_group is not failed
        fail_msg: 'Caddy group does not exist'
        success_msg: 'Caddy group exists'

    # Verify service is enabled and running (with retries for systemd startup)
    - name: Wait for systemd to be ready
      ansible.builtin.command:
        cmd: systemctl is-system-running
      register: systemd_status
      until: systemd_status.stdout in ['running', 'degraded']
      retries: 10
      delay: 3
      changed_when: false
      failed_when: false

    - name: Check Caddy service is enabled
      ansible.builtin.systemd:
        name: caddy
      register: caddy_service_status

    - name: Assert Caddy service is enabled
      ansible.builtin.assert:
        that:
          - caddy_service_status.status.UnitFileState == 'enabled'
        fail_msg: 'Caddy service is not enabled'
        success_msg: 'Caddy service is enabled'

    - name: Wait for Caddy service to be active
      ansible.builtin.systemd:
        name: caddy
      register: caddy_service_active
      until: caddy_service_active.status.ActiveState == 'active'
      retries: 10
      delay: 3

    - name: Assert Caddy service is running
      ansible.builtin.assert:
        that:
          - caddy_service_active.status.ActiveState == 'active'
        fail_msg: 'Caddy service is not running (state: {{ caddy_service_active.status.ActiveState }})'
        success_msg: 'Caddy service is running'

    # Verify Caddy is responding on port 8080
    - name: Wait for Caddy to respond on port 8080
      ansible.builtin.uri:
        url: http://localhost:8080
        return_content: true
      register: caddy_response
      until: caddy_response.status == 200
      retries: 10
      delay: 3

    - name: Assert Caddy responds correctly
      ansible.builtin.assert:
        that:
          - caddy_response.status == 200
          - "'OK' in caddy_response.content"
        fail_msg: 'Caddy did not respond correctly on port 8080'
        success_msg: 'Caddy is responding correctly on port 8080'

    # Final summary
    - name: Display verification summary
      ansible.builtin.debug:
        msg: |
          ============================================
          VERIFICATION COMPLETE - ALL CHECKS PASSED
          ============================================
          Binary:       /usr/local/bin/caddy ✓
          Version:      {{ caddy_version_output.stdout | trim }} ✓
          Module:       {{ expected_module }} ✓
          Config:       /etc/caddy/Caddyfile ✓
          Service:      enabled and running ✓
          HTTP Response: OK on port 8080 ✓
          ============================================
